import type { Metadata, NextPage } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

interface IRootLayoutProps {
	children: React.ReactNode
}

const RootLayout: NextPage<IRootLayoutProps> = ({ children }) => {
	return (
		<html lang='pt'>
			<body className={inter.className}>{children}</body>
		</html>
	)
}

export default RootLayout
