import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { withChildren } from '@/types/with-children.type'

import './globals.css'

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: React.FC<withChildren> = ({ children }) => {
  return (
    <html
      lang="en"
      className={inter.variable}
    >
      <body className="antialiased">{children}</body>
    </html>
  )
}

export default RootLayout
