import Navbar from '@/components/navbar'
import { Toaster } from '@/components/ui/toaster'
import CustomQueryClientProvider from '@/context/customQueryClientProvider'
import type { Metadata, NextPage } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

interface IRootLayoutProps {
	children: React.ReactNode
}

const RootLayout: NextPage<IRootLayoutProps> = ({ children }) => {
	return (
		<html lang='pt' className='dark'>
			<body className={`min-h-screen bg-background ${inter.className}`}>
				<CustomQueryClientProvider>
					<Navbar />
					<Toaster />
					{children}
				</CustomQueryClientProvider>
			</body>
		</html>
	)
}

export default RootLayout
