services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks:
      - devnet
    # depende do Mongo pra subir junto
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - devnet

volumes:
  mongo-data:

networks:
  devnet:
