import Navbar from '@/components/navbar'
import { Toaster } from '@/components/ui/toaster'
import AosProvider from '@/context/aosProvider'
import CustomQueryClientProvider from '@/context/customQueryClientProvider'
import type { Metadata, NextPage } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

interface IRootLayoutProps {
	children: React.ReactNode
	params: { locale: 'pt' | 'en' }
}

const RootLayout: NextPage<IRootLayoutProps> = ({ children, params }) => {
	return (
		<html lang={params.locale} className='dark'>
			<AosProvider />
			<body className={`min-h-screen bg-background ${inter.className} lg:flex`}>
				<CustomQueryClientProvider>
					<Navbar />
					<Toaster />
					{children}
				</CustomQueryClientProvider>
			</body>
		</html>
	)
}

export default RootLayout
