import Navbar from '@/components/navbar'
import { Toaster } from '@/components/ui/toaster'
import AosProvider from '@/context/aosProvider'
import CustomQueryClientProvider from '@/context/customQueryClientProvider'
import pick from 'lodash/pick'
import type { Metadata, NextPage } from 'next'
import { NextIntlClientProvider, useMessages } from 'next-intl'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

interface IRootLayoutProps {
	children: React.ReactNode
	params: { locale: 'pt' | 'en' }
}

const RootLayout: NextPage<IRootLayoutProps> = ({ children, params }) => {
	const messages = useMessages()

	return (
		<html lang={params.locale} className='dark'>
			<AosProvider />
			<body className={`min-h-screen bg-background ${inter.className} lg:flex`}>
				<NextIntlClientProvider
					messages={{
						...pick(messages, 'contactForm'),
						...pick(messages, 'languageSelector'),
					}}
				>
					<CustomQueryClientProvider>
						<Navbar />
						<Toaster />
						{children}
					</CustomQueryClientProvider>
				</NextIntlClientProvider>
			</body>
		</html>
	)
}

export default RootLayout
